backend:
  name: git-gateway
  branch: main   # или master, зависит от того, какая ветка у тебя на GitHub

media_folder: "images" # папка для загружаемых фото
public_folder: "/images"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"   # где будут храниться данные
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - { name: "description", label: "Описание", widget: "text" }
      - { name: "price", label: "Цена (€)", widget: "string" }
      - { name: "image", label: "Фото", widget: "image" }